@startuml Kommunikation
title Kandidat Kommunikationsautomat
[*] --> Uninitialized
Uninitialized : LED: Blue
Uninitialized--> Initialized: coap: /assign_color {color}
state Initialized {
    IDLE : LED: {color}
    Counting_Pushups: LED: {color}
    Winner: LED: Blinking [{color}, Off]
    Looser: LED: Off

    [*] --> IDLE
    IDLE --> Counting_Pushups: coap: /start
    Counting_Pushups --> Counting_Pushups: Pushup detected\n/ Notify observers:\n"/count" changed
    Counting_Pushups --> Winner: coap: /set_to_winner
    Counting_Pushups --> Looser: coap: /set_to_looser
}
Initialized --> Initialized: coap: /reset
@enduml
